### ISSUE TITLE
Should Description be above Syntax and Arguments/Values?

### ISSUE THREAD

**Issue by phoe** [phoe/clus-data#1]
Xach mentioned:
> I think on function pages, Syntax or Arguments and Values should precede the short summary, because the summary references the arguments.
> Since the description refers to terms in the syntax and arguments/values sections, i think they should precede it.
> It doesn't make sense to me to see: "**aref** - references _array_ at _index_" when there is no prior description of _array_ and _index_.

What do you guys think about it?

**Comment by sirherrbatka** [comment]
I agree with Xach.

**Comment by phoe** [comment]
So far I've counted five votes for this. I will be restoring description to its previous place and possibly opening an issue for creating summaries that will be in the descriptions' current places.

This issue will be closed once it is fixed.

**Comment by phoe** [comment]
Fixed in https://github.com/phoe/clus-data/commit/e7fcb5b3f05765606b1044322692004720290e7b.
